//
// Created by roei on 14/01/2020.
//

#ifndef SECONDMILESTONE__ASTARALGORITHM_H_
#define SECONDMILESTONE__ASTARALGORITHM_H_

class AStarAlgorithm {

};

#endif //SECONDMILESTONE__ASTARALGORITHM_H_
