//
// Created by roei on 14/01/2020.
//

#ifndef SECONDMILESTONE__BESTFSALGORITHM_H_
#define SECONDMILESTONE__BESTFSALGORITHM_H_

class BestFSAlgorithm {

};

#endif //SECONDMILESTONE__BESTFSALGORITHM_H_
